# master 数据源配置
master:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm_db
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
# second 数据源配置
second:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-data-jpa
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  type-aliases-package: com.cjrh.game_api.dao
#  mapper-locations: classpath*:mapper/*.xml
server:
  port: 7000
